### ISSUE TITLE
"Loading and pre-processing images" that seems to take forever.

### ISSUE THREAD

**Issue by loeiten** [acntech/fruit-classifier#12]
I have merged your branch into mine. Before the merging the training would take seconds, but the results bad. What changed after the merging was that when I start training, this starts a slow and tiresome "loading and pre-processing images" that seems to take forever. Is this the intention?

_Originally posted by @tordbb in https://github.com/acntech/fruit-classifier/pull/6#issuecomment-490143381_

**Comment by tordbb** [comment]
This seemed like a bug, but turned out to be a lack of optimisation. When the train function is run, it spends several seconds on preprocessing (shrinking and normalizing) every image before adding it to a pickle file. We might benefit from replacing the components of train/main() that do this job faster.
